### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by Gxinhu** [kkirchheim/accurate-classifiers-osr#1]
Hi,
Your code is awesome. I google your paper's name, but I do not find anything. If you are convenient, could you please share your paper, or upload it on Arxiv.

**Comment by kkirchheim** [comment]
Hi, unfortunately the paper has not been accepted for presentation at the BMVC. We are currently addressing the criticism and plan on publishing a revised form in the future. 

If you are looking for a project template, we would recommend [lightning-hydra-template](https://github.com/ashleve/lightning-hydra-template).

**Comment by Gxinhu** [comment]
Actually, I am trying to implement open set algorithms based on pytorch-lightning. Your code is totally understandable, even without paper. Thank you very much.
